#!/bin/bash

#PBS -N beagle
#PBS -l nodes=1:ppn=4
#PBS -l walltime=40:00:00
#PBS -o /projects/ps-gymreklab/helia/ensembl/phasing_st/phased/log
#PBS -e /projects/ps-gymreklab/helia/ensembl/phasing_st/phased/log
#PBS -A gymreklab-group
#PBS -q hotel
#PBS -V

cd /projects/ps-gymreklab/helia/ensembl/phasing_st/phased
source /projects/ps-gymreklab/helia/ensembl/venv_3.9/bin/activate

time ./beagle_phase.sh "$chr" "$file"
