#!/bin/bash

#PBS -N afreq
#PBS -l nodes=1:ppn=1
#PBS -l walltime=05:00:00
#PBS -o /projects/ps-gymreklab/helia/ensembl/experiments/allele_freq/log
#PBS -e /projects/ps-gymreklab/helia/ensembl/experiments/allele_freq/log
#PBS -A gymreklab-group
#PBS -q hotel
#PBS -V


source /projects/ps-gymreklab/helia/ensembl/venv_3.9/bin/activate

time statSTR \
	--vcf /projects/ps-gymreklab/helia/ensembl/ensemble_out/ensemble_chr"$chr"_filtered.vcf.gz  \
	--vcftype hipstr \
	--use-length \
	--afreq \
	--acount \
	--hwep \
	--het \
	--entropy \
	--mean \
	--var \
	--numcalled \
	--out /projects/ps-gymreklab/helia/ensembl/experiments/allele_freq/freqs/freqs_chr"$chr"
	#--samples /projects/ps-gymreklab/helia/ensembl/experiments/allele_freq/names/"$pop_name"_names.txt

