#!/bin/bash

#PBS -N methods
#PBS -l nodes=1:ppn=1
#PBS -l walltime=04:00:00
#PBS -o /projects/ps-gymreklab/helia/ensembl/experiments/upset_plot/log
#PBS -e /projects/ps-gymreklab/helia/ensembl/experiments/upset_plot/log
#PBS -V
#PBS -A gymreklab-group
#PBS -q hotel


echo $chr
zcat /projects/ps-gymreklab/helia/ensembl/ensemble_out/ensemble_chr"$chr"_dropped.vcf.gz  | grep -o -P 'METHODS.{0,8}' > /projects/ps-gymreklab/helia/ensembl/experiments/upset_plot/methods_chr"$chr".txt 


