#!/bin/bash

#PBS -N pca
#PBS -l nodes=1:ppn=5
#PBS -l walltime=80:00:00
#PBS -o /projects/ps-gymreklab/helia/ensembl/experiments/pca/log
#PBS -e /projects/ps-gymreklab/helia/ensembl/experiments/pca/log
#PBS -V
#PBS -A gymreklab-group
#PBS -q hotel

source /projects/ps-gymreklab/helia/ensembl/venv_3.9/bin/activate

zcat /projects/ps-gymreklab/helia/ensembl/ensemble_out/all/merged_all.vcf.gz | python3 /projects/ps-gymreklab/helia/ensembl/experiments/pca/vcf_mat.py

python3 /projects/ps-gymreklab/helia/ensembl/experiments/pca/pca_plot.py
