#!/bin/bash

#PBS -N impute
#PBS -l nodes=1:ppn=1
#PBS -l walltime=02:00:00
#PBS -o /projects/ps-gymreklab/helia/ensembl/1000Genomes-TR-Analysis/phasing/validation/log
#PBS -e /projects/ps-gymreklab/helia/ensembl/1000Genomes-TR-Analysis/phasing/validation/log
#PBS -A gymreklab-group
#PBS -q hotel
#PBS -V

source /projects/ps-gymreklab/helia/ensembl/venv_3.9/bin/activate

cd /projects/ps-gymreklab/helia/ensembl/1000Genomes-TR-Analysis/phasing/validation

./L1O.sh -s $sample -b beagle.19Apr22.7c0.jar  -c $chr -p $pop 

